export const metadata = {
  title: 'AAVORide | Safe & Secure Ride Sharing',
  description: 'Experience the best ride-sharing service with AAVORide. Fast, secure, and affordable transportation at your fingertips.',
  keywords: 'ride sharing, transportation, safe travel, AAVORide, taxi service',
  openGraph: {
    title: 'AAVORide',
    description: 'Safe and secure rides for everyone.',
    images: ['/images/hero-bg.jpg'], // This shows up when you share the link!
  },
};

'use client';
import { useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Poppins } from 'next/font/google';
import 'aos/dist/aos.css';
import './globals.css';

const poppins =Poppins({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
  display: 'swap'
});

export default function RootLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  return (
    <html lang="en">
      <head>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
      </head>
      <body>{children}</body>
    </html>
  );
}














/*
export const metadata = {
  title: 'AAVORide - Your Trusted Outstation Travel Partner',
  description: 'Easy cab booking for long-distance journeys, airport rides, and more.',
};







export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}









import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/
